"""
Configuration for the data.
"""

TICKERS = ["NVDA", "GOOG", "AAPL", "META", "MSFT", "AMZN", "TSLA", "NFLX", "ASML", "TSM"]
DAILY = "TIME_SERIES_DAILY"
DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED"
WINDOW_START = "2010-01-01"
WINDOW_END = "2019-12-31"
